version: '2'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /Users/utilisateur/Documents/GitHub/syam/volumes/database:/var/lib/mysql
  media:
    image: webapp-tweet
    links:
      - mysql:mysql
    ports:
      - 8081:8080
      - 9990:9990
      - 8787:8787
